[build]
  functions = "packages/server/build"
  publish = "packages/app/build"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "8.11.2"
  YARN_VERSION = "1.9.4"
  REACT_APP_ENVIRONMENT = "netlify"