name: run-check-types
on: ['push']
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: lerna run build --scope @won/core
      - run: npm run install-all
      - run: lerna run check-types
