name: run-test
on: ["push"]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # Generate types for core package
      - run: lerna run build --scope @won/core
      # Install project dependencies
      - run: npm run install-all
      # install fauna cli
      - run: npm install -g fauna-shell
      # setup local fauna database
      - run: npm run fauna-dev
      # Set needed envs
      - run: export $(grep -v '^#' .env.test | xargs)
      # run tests
      - run: lerna run test
