name: run-test
on: ["push"]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Install project dependencies
      - run: npm run install-all
      # Generate types for core package
      - run: lerna run build --scope @won/core 
      # install fauna cli
      - run: npm install -g fauna-shell
      # setup local fauna database
      - run: npm run fauna-dev
      # run tests
      - run: lerna run test